# Generated by Django 4.1.3 on 2022-11-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myapp',
            new_name='students',
        ),
    ]
